---
title: "| \\vspace{5cm} \\Huge Car Price Prediction \n\n| and \n\n| \\ \\Huge Heart
  Disease Classification\n"
author: |
  | \vspace{0.5cm} \LARGE Hamid Hamidi, Thet Nyein, and Yanzhao Qian
  | \small Authors are in alphabetic order and have equal contribution.
output:
  pdf_document:
    extra_dependencies:
    - bbm
    - xcolor
fontsize: 12
bibliography: references.bib
csl: citation_style.csl
---
\pagebreak


\newpage
\tableofcontents


\pagebreak

# Abstract

Generalized Linear Models (GLMs) are the extension of the ordinary linear regression models. GLMs enable us to use different distributions for the response with distinctive link functions @GLMintroduction. Here, we use two different data sets to show the broad applications of the GLMs in real-world problems, one of which is the "Car Price Prediction" @carprice, and the other is "Heart Failure prediction" @heartdata. In our analyses, we focus on model fitting and highlighting the most important variables instead of predicting desired outcomes and their accuracy. Our study of each data set is reported in its corresponding section. In the following, we discuss why we have chosen these data sets and provide a detailed description of our analyses along with the reasons and intuitions behind them. In both of these studies, all analyses were performed using the R programming language @R-base.

\pagebreak



# Car Price Prediction

## Introduction

One of the largest automotive markets in the world is the USA car market @carmarketUSA. Since 1982, when Honda invested in the USA car market, many other companies have been joining and competing in the USA car market resulting in foreign investment of more than 110 billion dollars @carmarketUSA. These days, with skilled workers, local and governmental supports, a huge consumer market, and many other reasons, the USA car market is a primer market in the car industry. A new Chinese car company wants to join and compete in the USA car market. In the following, our goal is to identify significant variables affecting the car price and quantify their significance. These analyses are usually performed by a third party, such as a consulting company, or the business strategy division of the investing company. According to our findings, they can manipulate many variables, such as the car design, to have a better business strategy to enter the USA car market. These analyses can directly affect the success of billions of dollars investment. Consequently, our analyses are vital and should be detailed and valid.

We found out the car price (response) distribution is quite close to the Gamma distribution; therefore, we used the GLM with Gamma distribution and logarithmic link function to model the price of cars for distinctive variables. We also suspected that it might be possible to model the logarithm of price with Gaussian distribution and identity link function. However, the distribution of the logarithmic price is not close to the Normal distribution. Consequently, we only used the Gamma distribution with the logarithmic link function. We performed variable selection and selected the most reasonable model (details in the Statistical Analyses section). 

Using these analyses, we were able to identify several significant variables contributing to the car price, such as the car manufacturer (or the so-called brand of the car), the engine location (cars with rear engines are usually sport cars with higher prices), and the engine size (the bigger the higher the price).

Our data set, and consequently, our analyses have some limitations as well. For instance, electric cars are more than 2.5% of the USA car market @electricmarket but are not included in our data set. Additionally, luxury brands such as Rolls-Royce and Lincoln are missing. Furthermore, the majority of sport cars are missing in our data set, showing our limitation in analyzing the sport and luxury car price variables. In the following, we present a detailed description of our analysis, methods, and results. 




## Data Collection and exploration

## Statistical Analyses

## Conclusion

\pagebreak

# Heart Disease Classification

## Introduction

Heart Failure, also know as cognitive heart failure, can broadly be defined as a condition that happens when heart is unable to supply body's need for Oxygen and blood @HeartFailure. According to the latest annual statistical report from the American Heart Association and the National Institutes of Health, about 6.2 million adults in the United States have heart failure @virani2020heart. Furthermore, in 2018, heart failure was mentioned on 379,800 death certificates (13.4%) @virani2020heart and cost about $30 billion annually @benjamin2019heart. 

This suggests that identifying the core health behaviors and risk factors influencing the heart failure is critical not only for our community health but also for our economy. Therefore, we decided to analyze the "Heart Failure prediction" data set @heartdata to find variables playing a key role in heart failure. As the response in our data set is binary (0 or 1), we used the logistic regression to model the probability of having a heart failure. Moreover, we performed variable selection to select the best model and determine most important factors in heart failure (details in the Statistical Analyses section).

This study has generally revealed causal factors in heart failure such as sex, exercise angina (a type of chest pain during performing exercises), distinctive types of chest pain, and squared of Cholesterol level. 

The generalisability of our results is subject to certain limitations. For instance, our data set does not cover ages younger than 28 which will cause the analyses be biased toward older ages. Another issue that was not addressed in this study was the mortality of the patients. This might not seem arguable at the first look. However, most of the patients with asymptomatic chest pain might have lived without any critical problems through their lives and patients with other types of chest pain might have faced devastating situations. This might cause our findings to be questionable from different perspectives. 

## Data Collection and exploration

## Statistical Analyses

### 3 GLM models and stepwise AIC selection

To begin with, let's assign each feature with a variable name.




\begin{tabular}{ |p{2.3cm}|p{3cm}|p{9cm}|p{0.7cm}|  }
 \hline
 \multicolumn{4}{|c|}{Data Dictionary} \\
 \hline
 Variable Name & Definition & Explanation & Vari- able name\\
 \hline
    Age   &   age of the patient    &   years   &   $x_1$   \\ 
   Sex   &   sex of the patient   &   M: Male, F: Female   &   $x_2$   \\ 
   ChestPainType   &   chest pain type   &   TA: Typical Angina, ATA: Atypical Angina, NAP: Non-Anginal Pain, ASY: Asymptomatic   &   $x_3$   \\ 
   RestingBP   &   resting blood pressure    &   mm Hg   &   $x_4$   \\ 
   Cholesterol   &   serum cholesterol   &   1: if FastingBS > 120 mg/dl, 0: otherwise   &   $x_5$   \\ 
   FastingBS   &   fasting blood sugar   &   Normal: Normal, ST: having ST-T wave abnormality (T wave inversions and/or ST elevation or depression of > 0.05 mV), LVH: showing probable or definite left ventricular hypertrophy by Estes' criteria   &   $x_6$   \\ 
   RestingECG   &   resting electrocardiogram results   &   Numeric value between 60 and 202   &   $x_7$   \\ 
   MaxHR   &   maximum heart rate achieved   &   Y: Yes, N: No   &   $x_8$   \\ 
   ExerciseAngina   &    exercise-induced angina    &   Numeric value measured in depression   &   $x_9$   \\ 
   Oldpeak   &   oldpeak = ST    &   Numeric value measured in depression   &   $x_{10}$   \\ 
   ST\_Slope   &   the slope of the peak exercise ST segment    &   Up: upsloping, Flat: flat, Down: downsloping   &   $x_{11}$   \\ 
   HeartDisease   &   output class   &   1: heart disease, 0: Normal   &   $y$   \\ 

 \hline
 \end{tabular}
 
 Since the response is having heart disease or not, it is a binomial distributed response. So it is suggested we could use a logistic regression model.
 At first, we created a logistic model of all the main effects, and the formula of the model is
$$
\log \frac{p}{1-p} = \beta_0 + \sum_{i=1}^{11} \beta_i x_i
$$
where $p$ is the probability to get the heart disease, and $\beta_i, i = 1,2, \dots, 11$ is the coefficients of the parameter, $\beta_0$ is the intercept. 
So we fitted the model, and got the estimated shown in the table below.

***********************a model


 
### Analysis of the 3 Models

1. ROC, Deviance Test, Pseudo-R square, 

## Conclusion


# Appendix

# References